name: "elixir_bot"
author: "clszzyh"
description: "A Github Bot by Elixir."
branding:
  icon: code
  color: gray-dark
inputs:
  token:
    description: "Github Token"
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/clszzyh/elixir_bot:main"
  args:
    - "-token"
    - ${{ inputs.token }}
